
import { BrazilianState, MusicGenre, PromotionType, RadioProfile } from './types';

export const BRAZILIAN_STATES: BrazilianState[] = [
  { name: 'Acre', uf: 'AC' },
  { name: 'Alagoas', uf: 'AL' },
  { name: 'Amapá', uf: 'AP' },
  { name: 'Amazonas', uf: 'AM' },
  { name: 'Bahia', uf: 'BA' },
  { name: 'Ceará', uf: 'CE' },
  { name: 'Distrito Federal', uf: 'DF' },
  { name: 'Espírito Santo', uf: 'ES' },
  { name: 'Goiás', uf: 'GO' },
  { name: 'Maranhão', uf: 'MA' },
  { name: 'Mato Grosso', uf: 'MT' },
  { name: 'Mato Grosso do Sul', uf: 'MS' },
  { name: 'Minas Gerais', uf: 'MG' },
  { name: 'Pará', uf: 'PA' },
  { name: 'Paraíba', uf: 'PB' },
  { name: 'Paraná', uf: 'PR' },
  { name: 'Pernambuco', uf: 'PE' },
  { name: 'Piauí', uf: 'PI' },
  { name: 'Rio de Janeiro', uf: 'RJ' },
  { name: 'Rio Grande do Norte', uf: 'RN' },
  { name: 'Rio Grande do Sul', uf: 'RS' },
  { name: 'Rondônia', uf: 'RO' },
  { name: 'Roraima', uf: 'RR' },
  { name: 'Santa Catarina', uf: 'SC' },
  { name: 'São Paulo', uf: 'SP' },
  { name: 'Sergipe', uf: 'SE' },
  { name: 'Tocantins', uf: 'TO' },
];

export const BUSINESS_CATEGORIES: string[] = [
    "Gestor Artístico",
    "Divulgador",
    "Empresário Artístico",
    "Promotor de Eventos",
    "Empresário",
    "Casa de Shows",
    "Outro"
];

export const MUSIC_GENRES: MusicGenre[] = Object.values(MusicGenre);

export const PROMOTION_TYPES: PromotionType[] = Object.values(PromotionType);

export const RADIO_PROFILES: RadioProfile[] = [
    RadioProfile.POPULAR,
    RadioProfile.SERTANEJO,
    RadioProfile.POPROCK,
    RadioProfile.EVANGELICA,
    RadioProfile.JORNALISMO,
    RadioProfile.OUTRO,
];

export const DDD_REGIONS: Record<string, { state: string; cities: string[]; lat: number; lng: number }> = {
    '11': { state: 'SP', cities: ['São Paulo', 'Guarulhos', 'Osasco'], lat: -23.5505, lng: -46.6333 },
    '12': { state: 'SP', cities: ['São José dos Campos', 'Taubaté', 'Guaratinguetá'], lat: -23.1791, lng: -45.8872 },
    '13': { state: 'SP', cities: ['Santos', 'São Vicente', 'Guarujá'], lat: -23.9608, lng: -46.3336 },
    '14': { state: 'SP', cities: ['Bauru', 'Marília', 'Jaú'], lat: -22.3145, lng: -49.0601 },
    '15': { state: 'SP', cities: ['Sorocaba', 'Itapetininga', 'Tatuí'], lat: -23.501, lng: -47.458 },
    '16': { state: 'SP', cities: ['Ribeirão Preto', 'Franca', 'Araraquara'], lat: -21.1767, lng: -47.8103 },
    '17': { state: 'SP', cities: ['São José do Rio Preto', 'Barretos', 'Catanduva'], lat: -20.8202, lng: -49.3797 },
    '18': { state: 'SP', cities: ['Presidente Prudente', 'Araçatuba', 'Andradina'], lat: -22.122, lng: -51.385 },
    '19': { state: 'SP', cities: ['Campinas', 'Piracicaba', 'Limeira'], lat: -22.906, lng: -47.061 },
    '21': { state: 'RJ', cities: ['Rio de Janeiro', 'Niterói', 'Duque de Caxias'], lat: -22.9068, lng: -43.1729 },
    '22': { state: 'RJ', cities: ['Campos dos Goytacazes', 'Cabo Frio', 'Macaé'], lat: -21.752, lng: -41.332 },
    '24': { state: 'RJ', cities: ['Volta Redonda', 'Petrópolis', 'Barra Mansa'], lat: -22.522, lng: -44.104 },
    '27': { state: 'ES', cities: ['Vitória', 'Vila Velha', 'Serra'], lat: -20.319, lng: -40.337 },
    '28': { state: 'ES', cities: ['Cachoeiro de Itapemirim', 'Guarapari', 'Castelo'], lat: -20.846, lng: -41.114 },
    '31': { state: 'MG', cities: ['Belo Horizonte', 'Contagem', 'Betim'], lat: -19.9167, lng: -43.9345 },
    '32': { state: 'MG', cities: ['Juiz de Fora', 'Barbacena', 'Ubá'], lat: -21.764, lng: -43.349 },
    '33': { state: 'MG', cities: ['Governador Valadares', 'Teófilo Otoni', 'Ipatinga'], lat: -18.851, lng: -41.949 },
    '34': { state: 'MG', cities: ['Uberlândia', 'Uberaba', 'Patos de Minas'], lat: -18.918, lng: -48.277 },
    '35': { state: 'MG', cities: ['Poços de Caldas', 'Varginha', 'Pouso Alegre'], lat: -21.791, lng: -46.564 },
    '37': { state: 'MG', cities: ['Divinópolis', 'Itaúna', 'Formiga'], lat: -20.139, lng: -44.885 },
    '38': { state: 'MG', cities: ['Montes Claros', 'Curvelo', 'Januária'], lat: -16.735, lng: -43.861 },
    '41': { state: 'PR', cities: ['Curitiba', 'São José dos Pinhais', 'Pinhais'], lat: -25.4284, lng: -49.2733 },
    '42': { state: 'PR', cities: ['Ponta Grossa', 'Guarapuava', 'Irati'], lat: -25.0945, lng: -50.1633 },
    '43': { state: 'PR', cities: ['Londrina', 'Apucarana', 'Arapongas'], lat: -23.310, lng: -51.162 },
    '44': { state: 'PR', cities: ['Maringá', 'Umuarama', 'Campo Mourão'], lat: -23.425, lng: -51.938 },
    '45': { state: 'PR', cities: ['Foz do Iguaçu', 'Cascavel', 'Toledo'], lat: -25.546, lng: -54.588 },
    '46': { state: 'PR', cities: ['Francisco Beltrão', 'Pato Branco', 'Dois Vizinhos'], lat: -26.081, lng: -53.055 },
    '47': { state: 'SC', cities: ['Joinville', 'Blumenau', 'Itajaí'], lat: -26.303, lng: -48.845 },
    '48': { state: 'SC', cities: ['Florianópolis', 'São José', 'Criciúma'], lat: -27.595, lng: -48.548 },
    '49': { state: 'SC', cities: ['Chapecó', 'Lages', 'Concórdia'], lat: -27.096, lng: -52.618 },
    '51': { state: 'RS', cities: ['Porto Alegre', 'Canoas', 'Gravataí'], lat: -30.0346, lng: -51.2177 },
    '53': { state: 'RS', cities: ['Pelotas', 'Rio Grande', 'Bagé'], lat: -31.771, lng: -52.337 },
    '54': { state: 'RS', cities: ['Caxias do Sul', 'Passo Fundo', 'Bento Gonçalves'], lat: -29.168, lng: -51.179 },
    '55': { state: 'RS', cities: ['Santa Maria', 'Uruguaiana', 'Santana do Livramento'], lat: -29.684, lng: -53.806 },
    '61': { state: 'DF', cities: ['Brasília', 'Taguatinga', 'Ceilândia'], lat: -15.7942, lng: -47.8825 },
    '62': { state: 'GO', cities: ['Goiânia', 'Aparecida de Goiânia', 'Anápolis'], lat: -16.686, lng: -49.264 },
    '63': { state: 'TO', cities: ['Palmas', 'Araguaína', 'Gurupi'], lat: -10.184, lng: -48.333 },
    '64': { state: 'GO', cities: ['Rio Verde', 'Caldas Novas', 'Itumbiara'], lat: -17.797, lng: -50.925 },
    '65': { state: 'MT', cities: ['Cuiabá', 'Várzea Grande', 'Rondonópolis'], lat: -15.601, lng: -56.097 },
    '66': { state: 'MT', cities: ['Sinop', 'Lucas do Rio Verde', 'Sorriso'], lat: -11.861, lng: -55.503 },
    '67': { state: 'MS', cities: ['Campo Grande', 'Dourados', 'Três Lagoas'], lat: -20.442, lng: -54.646 },
    '68': { state: 'AC', cities: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira'], lat: -9.974, lng: -67.81 },
    '69': { state: 'RO', cities: ['Porto Velho', 'Ji-Paraná', 'Ariquemes'], lat: -8.761, lng: -63.903 },
    '71': { state: 'BA', cities: ['Salvador', 'Lauro de Freitas', 'Camaçari'], lat: -12.9777, lng: -38.5016 },
    '73': { state: 'BA', cities: ['Itabuna', 'Ilhéus', 'Porto Seguro'], lat: -14.789, lng: -39.283 },
    '74': { state: 'BA', cities: ['Juazeiro', 'Irecê', 'Jacobina'], lat: -9.412, lng: -40.501 },
    '75': { state: 'BA', cities: ['Feira de Santana', 'Alagoinhas', 'Serrinha'], lat: -12.266, lng: -38.966 },
    '77': { state: 'BA', cities: ['Vitória da Conquista', 'Barreiras', 'Guanambi'], lat: -14.866, lng: -40.839 },
    '79': { state: 'SE', cities: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto'], lat: -10.916, lng: -37.067 },
    '81': { state: 'PE', cities: ['Recife', 'Jaboatão dos Guararapes', 'Olinda'], lat: -8.057, lng: -34.882 },
    '82': { state: 'AL', cities: ['Maceió', 'Arapiraca', 'Rio Largo'], lat: -9.665, lng: -35.735 },
    '83': { state: 'PB', cities: ['João Pessoa', 'Campina Grande', 'Santa Rita'], lat: -7.119, lng: -34.862 },
    '84': { state: 'RN', cities: ['Natal', 'Mossoró', 'Parnamirim'], lat: -5.795, lng: -35.209 },
    '85': { state: 'CE', cities: ['Fortaleza', 'Caucaia', 'Maracanaú'], lat: -3.732, lng: -38.526 },
    '86': { state: 'PI', cities: ['Teresina', 'Parnaíba', 'Picos'], lat: -5.09, lng: -42.801 },
    '87': { state: 'PE', cities: ['Petrolina', 'Caruaru', 'Garanhuns'], lat: -9.397, lng: -40.501 },
    '88': { state: 'CE', cities: ['Juazeiro do Norte', 'Sobral', 'Crato'], lat: -7.212, lng: -39.315 },
    '89': { state: 'PI', cities: ['Floriano', 'São Raimundo Nonato', 'Corrente'], lat: -6.769, lng: -43.023 },
    '91': { state: 'PA', cities: ['Belém', 'Ananindeua', 'Castanhal'], lat: -1.455, lng: -48.502 },
    '92': { state: 'AM', cities: ['Manaus', 'Parintins', 'Itacoatiara'], lat: -3.119, lng: -60.021 },
    '93': { state: 'PA', cities: ['Santarém', 'Itaituba', 'Oriximiná'], lat: -2.443, lng: -54.708 },
    '94': { state: 'PA', cities: ['Marabá', 'Parauapebas', 'Redenção'], lat: -5.368, lng: -49.073 },
    '95': { state: 'RR', cities: ['Boa Vista', 'Rorainópolis', 'Caracaraí'], lat: 2.823, lng: -60.675 },
    '96': { state: 'AP', cities: ['Macapá', 'Santana', 'Laranjal do Jari'], lat: 0.038, lng: -51.066 },
    '97': { state: 'AM', cities: ['Tefé', 'Tabatinga', 'Coari'], lat: -3.353, lng: -64.711 },
    '98': { state: 'MA', cities: ['São Luís', 'Imperatriz', 'São José de Ribamar'], lat: -2.53, lng: -44.302 },
    '99': { state: 'MA', cities: ['Caxias', 'Timon', 'Codó'], lat: -4.86, lng: -43.358 },
};